# Generated by Django 5.2.4 on 2025-08-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='document_type',
            field=models.CharField(choices=[('pan', 'PAN Card'), ('address', 'Address Proof'), ('registration', 'Business Registration'), ('id', 'ID Proof'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('service', 'Service'), ('it', 'Information Technology'), ('hospitality', 'Hospitality'), ('other', 'Other')], max_length=50),
        ),
    ]
